version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS_URL=$REDIS_URL
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh redis:6379 -- node src/server.js
  
  redis:
    image: redis:5.0.5-alpine
    container_name: cache
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS_URL=$REDIS_URL
    expose: 
      - 6379
    networks:
      - app-network 

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:  
