version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: oderayi/stock-ticker-node
    container_name: stock-ticker-app
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS_URL=$REDIS_URL
      - ALPHA_VANTAGE_API_KEY=$ALPHA_VANTAGE_API_KEY
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    networks:
      - stock-ticker-network
    command: ./wait-for.sh redis:6379 -- nodemon
    depends_on:
    - redis
  
  redis:
    image: redis:5.0.5-alpine
    container_name: stock-ticker-cache
    restart: unless-stopped
    ports: ["6379"]
    networks:
      - stock-ticker-network 
    volumes:
    - redis-data:/data
    command: redis-server --appendonly yes

networks:
  stock-ticker-network:
    driver: bridge

volumes:
  redis-data:
