version: '3'

services:
  app:
    image: oderayi/stock-ticker-node:latest
    container_name: stock-ticker-app-container
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://stock-ticker-cache-container
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - stock-ticker-network
    command: ./wait-for.sh redis:6379 -- node src/server.js
    depends_on:
    - redis
  
  redis:
    image: redis:5.0.5-alpine
    container_name: stock-ticker-cache-container
    restart: unless-stopped
    expose: 
      - 6379
    networks:
      - stock-ticker-network 
    volumes:
    - redis-data:/data
    command: redis-server --appendonly yes

networks:
  stock-ticker-network:
    driver: bridge

volumes:
  node_modules:  
  redis-data:
